language: c
compiler: gcc

before_install:
        - sudo apt-get install -y valgrind
        - cd tests/unit-tests/
install: make ../../cspec/release/libcspecs.so

script: make valgrind

branches:
  only: master

notifications:
  email:
    - gastonprietoutn@gmail.com
    - mngi0410@gmail.com
    - J@florius.com.ar
